#!/usr/bin/env bash
# Build docs/erw-working-paper.tex + docs/erw-working-paper.pdf from
# docs/erw-working-paper.md.
#
# The Markdown file is the canonical source of truth.

set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$HERE"

MD="erw-working-paper.md"
TEX="erw-working-paper.tex"
PDF="erw-working-paper.pdf"

if [[ ! -f "$MD" ]]; then
  echo "error: $MD not found in $HERE" >&2
  exit 1
fi

echo "==> pandoc: $MD -> $TEX"
pandoc -f markdown -t latex "$MD" \
  -o "$TEX" \
  --standalone \
  --toc \
  --number-sections \
  --pdf-engine=xelatex \
  --top-level-division=section \
  -V documentclass=article \
  -V fontsize=11pt \
  -V geometry:margin=2.4cm \
  -V colorlinks=true \
  -V linkcolor=NavyBlue \
  -V urlcolor=NavyBlue \
  -V toccolor=NavyBlue \
  -V mainfont="Helvetica Neue" \
  -V monofont="Menlo" \
  -V title="A Geospatial Ex-Ante Profitability Model for Basalt Enhanced Rock Weathering in Sub-Saharan Africa" \
  -V subtitle="Working Paper" \
  -V author="Bisrat Haile" \
  -V date="$(date +%Y-%m-%d)" \
  --include-in-header="erw-working-paper-header.tex"

{
  echo "% =====================================================================";
  echo "% AUTO-GENERATED from docs/erw-working-paper.md by";
  echo "% docs/build-erw-working-paper.sh. Do NOT edit this file directly --";
  echo "% your changes will be overwritten on the next rebuild. Edit the .md";
  echo "% and re-run build-erw-working-paper.sh.";
  echo "% =====================================================================";
  cat "$TEX";
} > "$TEX.tmp" && mv "$TEX.tmp" "$TEX"

echo "==> xelatex pass 1"
xelatex -interaction=nonstopmode -halt-on-error "$TEX" > /dev/null

echo "==> xelatex pass 2 (cross-refs)"
xelatex -interaction=nonstopmode -halt-on-error "$TEX" > /dev/null

rm -f erw-working-paper.aux erw-working-paper.log erw-working-paper.out erw-working-paper.toc

pages=$(pdfinfo "$PDF" 2>/dev/null | awk '/^Pages:/ {print $2}')
size=$(du -h "$PDF" | cut -f1)
echo "==> wrote $PDF (${pages:-?} pages, $size)"
