#!/usr/bin/env bash
# Build docs/erw-model.tex + docs/erw-model.pdf from docs/erw-model.md.
#
# The Markdown file is the canonical source of truth — edit erw-model.md, not
# erw-model.tex (which is regenerated each time this script runs).
#
# Dependencies: pandoc, xelatex (TeX Live or MiKTeX), pdftocairo (poppler).
# Run from the repo root or from docs/.

set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$HERE"

MD="erw-model.md"
TEX="erw-model.tex"
PDF="erw-model.pdf"

if [[ ! -f "$MD" ]]; then
  echo "error: $MD not found in $HERE" >&2
  exit 1
fi

echo "==> pandoc: $MD -> $TEX"
pandoc -f markdown -t latex "$MD" \
  -o "$TEX" \
  --standalone \
  --toc \
  --pdf-engine=xelatex \
  --top-level-division=section \
  -V documentclass=article \
  -V fontsize=11pt \
  -V geometry:margin=2.3cm \
  -V colorlinks=true \
  -V linkcolor=NavyBlue \
  -V urlcolor=NavyBlue \
  -V toccolor=NavyBlue \
  -V mainfont="Helvetica Neue" \
  -V monofont="Menlo" \
  -V title="Ex-Ante ERW Model --- Living Documentation" \
  -V subtitle="Geospatial profitability model for Enhanced Rock Weathering with basalt in Sub-Saharan Africa" \
  -V date="$(date +%Y-%m-%d)" \
  --include-in-header="erw-model-header.tex"

# Prepend an "auto-generated, do not edit" header so anyone opening the .tex
# directly is told to edit the .md instead.
{
  echo "% =====================================================================";
  echo "% AUTO-GENERATED from docs/erw-model.md by docs/build-erw-model.sh.";
  echo "% Do NOT edit this file directly — your changes will be overwritten on";
  echo "% the next rebuild. Edit erw-model.md and re-run build-erw-model.sh.";
  echo "% =====================================================================";
  cat "$TEX";
} > "$TEX.tmp" && mv "$TEX.tmp" "$TEX"

echo "==> xelatex pass 1"
xelatex -interaction=nonstopmode -halt-on-error "$TEX" > /dev/null

echo "==> xelatex pass 2 (cross-refs)"
xelatex -interaction=nonstopmode -halt-on-error "$TEX" > /dev/null

# Clean intermediate files
rm -f erw-model.aux erw-model.log erw-model.out erw-model.toc

pages=$(pdfinfo "$PDF" 2>/dev/null | awk '/^Pages:/ {print $2}')
size=$(du -h "$PDF" | cut -f1)
echo "==> wrote $PDF (${pages:-?} pages, $size)"
