#!/usr/bin/env bash
# Build docs/erw-tutorial.tex + docs/erw-tutorial.pdf from docs/erw-tutorial.md.
# The Markdown file is the canonical source of truth.

set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$HERE"

MD="erw-tutorial.md"
TEX="erw-tutorial.tex"
PDF="erw-tutorial.pdf"

echo "==> pandoc: $MD -> $TEX"
pandoc -f markdown -t latex "$MD" \
  -o "$TEX" \
  --standalone \
  --toc \
  --pdf-engine=xelatex \
  --top-level-division=section \
  -V documentclass=article \
  -V fontsize=11pt \
  -V geometry:margin=2.5cm \
  -V colorlinks=true \
  -V linkcolor=NavyBlue \
  -V urlcolor=NavyBlue \
  -V toccolor=NavyBlue \
  -V mainfont="Helvetica Neue" \
  -V monofont="Menlo" \
  -V title="A Tutorial on the Ex-Ante ERW Project" \
  -V subtitle="What the model does, in plain language" \
  -V author="Bisrat Haile" \
  -V date="$(date +%Y-%m-%d)" \
  --include-in-header="erw-tutorial-header.tex"

{
  echo "% =====================================================================";
  echo "% AUTO-GENERATED from docs/erw-tutorial.md by docs/build-erw-tutorial.sh.";
  echo "% Do NOT edit this file directly -- edit the .md and re-run the script.";
  echo "% =====================================================================";
  cat "$TEX";
} > "$TEX.tmp" && mv "$TEX.tmp" "$TEX"

echo "==> xelatex pass 1"
xelatex -interaction=nonstopmode -halt-on-error "$TEX" > /dev/null

echo "==> xelatex pass 2 (cross-refs)"
xelatex -interaction=nonstopmode -halt-on-error "$TEX" > /dev/null

rm -f erw-tutorial.aux erw-tutorial.log erw-tutorial.out erw-tutorial.toc

pages=$(pdfinfo "$PDF" 2>/dev/null | awk '/^Pages:/ {print $2}')
size=$(du -h "$PDF" | cut -f1)
echo "==> wrote $PDF (${pages:-?} pages, $size)"
